Repository GPII/windows, pull requests merged in 2020-05, with the labels that each got.

#309 GPII-4420: Only listing languages installed by a morphic language msi
  gpii/node_modules/WindowsUtilities/WindowsUtilities.js
  gpii/node_modules/gpii-localisation/src/language.js
Labels: 1.3.x

#257 GPII-3830: Detect if a drive exists before opening it.
  gpii/node_modules/WindowsUtilities/WindowsUtilities.js
  gpii/node_modules/WindowsUtilities/test/WindowsUtilitiesTests.js
Labels: 1.3.x

#277 GPII-4092: QSS failing due to no sound card.
  gpii/node_modules/nativeSettingsHandler/src/nativeSettingsHandler.js
Labels: 1.3.x

#307 GPII-4409: MYOB launchers activate an existing application instance.
  gpii/node_modules/WindowsUtilities/WindowsUtilities.js
  gpii/node_modules/gpii-userInput/test/manualSendKeys.js
  gpii/node_modules/processHandling/processHandling.js
  gpii/node_modules/processHandling/test/test-window.cs
  gpii/node_modules/processHandling/test/testProcessHandling.js
Labels: 1.3.x, Priority

#276 GPII-4087: Added hack to stop wallpaper being reset.
  gpii/node_modules/WindowsUtilities/WindowsUtilities.js
  gpii/node_modules/WindowsUtilities/test/WindowsUtilitiesTests.js
  gpii/node_modules/spiSettingsHandler/src/SpiSettingsHandler.js
Labels: 1.3.x, Needs Work, Priority

#319 GPII-4486 Returning only the settings asked for in the payload
  gpii/node_modules/displaySettingsHandler/src/displaySettingsHandler.js
  package.json
Labels: Morphic 1.3.5

#322 GPII-4470: Storing the currently active window in an environment variable
  gpii/node_modules/gpii-app-zoom/src/appZoom.js
Labels: Morphic 1.3.5
